### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.

### ISSUE THREAD

**Issue by marianogoldman** [pestphp/pest-intellij#149] opened 2021-08-01 11:37 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.0.1
| Pest version     | x.y.z
| IntelliJ version | PS-212.4746.100
| OS               | Linux

### Stacktrace
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PHP file, file.class=class com.jetbrains.php.lang.psi.PhpFileImpl, file.lang=Language: PHP, modStamp=2
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
latestIndexedStub=null
 viewProvider=com.jetbrains.php.lang.PhpFileViewProvider{vFile=file:///home/mariano/dev/ark/btcd/vendor/Expectation.php, vFileId=66637, content=VirtualFileContent{size=81}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1627683313387; file length: 81
 doc saved: true; doc stamp: 0; doc size: 0; committed: true
indexing info: indexing timestamp = 1627683313387, binary = false, byte size = 81, char size = 81
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:242)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:240)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:61)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:193)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:212)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:731)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:934)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:741)
	at com.pestphp.pest.ExpectUtilKt.getExpectExtends(ExpectUtil.kt:85)
	at com.pestphp.pest.fileListeners.ExtendAsyncFileListener.updateFile(ExtendAsyncFileListener.kt:35)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase$processRecursively$1.visitFile(AsyncFileChangeListenerBase.kt:59)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:108)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:293)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase.processRecursively(AsyncFileChangeListenerBase.kt:56)
	at com.intellij.openapi.externalSystem.autoimport.AsyncFileChangeListenerBase.process(AsyncFileChangeListenerBase.kt:44)
	at com.intellij.openapi.externalSystem.autoimport.A
```

**Comment by olivernybroe** [comment] 2021-08-01 19:29
Duplicate of #148

**Closed by olivernybroe** 2021-08-01 19:29 UTC
