### ISSUE TITLE
Default Pest.php configuration not detecting applicable tests

### ISSUE THREAD

**Issue by scheMeZa** [pestphp/pest-intellij#457] opened 2023-05-11 09:07 UTC
**Describe the bug**
This bug is specific to endpoint testing. PhpStorm does not recognise `$this->get(...)` or any other endpoint function. Thus it also does not know what `$response` is in this example: `$response = $this->get(...)`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a new project with a clean install of Pest as described by the installation guide.
1. The generated `Pest.php` file looks like this by default:
```php
...

uses(
    Tests\TestCase::class,
    // Illuminate\Foundation\Testing\RefreshDatabase::class,
)->in('Feature');

...
```
1. Create a new endpoint test: `php artisan make:test --pest Routes/HomePageRouteTest`
1. PhpStorm doesn't know what `$this->get(...)` is, and thus autocomplete and suggestions do not work:
![image](https://github.com/pestphp/pest-intellij/assets/7773361/c8791e29-15a9-451a-bcb2-4fdbb755147a)
![image](https://github.com/pestphp/pest-intellij/assets/7773361/e213c5d7-ca18-4062-8ae8-bcd10503ece1)

**Expected behaviour**
I expect to be able to use autocomplete and suggestions on native testing functions. They speed up development by a lot.

**Desktop (please complete the following information):**
 - OS: Windows
 - IntelliJ Version: 2023.1.1
 - Plugin Version 1.9.2

**Comment by scheMeZa** [comment] 2023-05-11 09:09
I have found a workaround for the issue. I'm taking screenshots and will post below.

**Comment by scheMeZa** [comment] 2023-05-11 09:11
Updating `Pest.php` to discover tests like this fixes the issue:
```php
...
uses(Tests\TestCase::class)->in('./');
...
```
![image](https://github.com/pestphp/pest-intellij/assets/7773361/21136ad1-d689-4c05-944a-58697f1ec34e)
![image](https://github.com/pestphp/pest-intellij/assets/7773361/e982245b-81c5-4ac7-b26e-70f475ece73d)
![image](https://github.com/pestphp/pest-intellij/assets/7773361/d1148acd-ba7f-41bc-8cd9-8c29aa2d43c3)

**Comment by olivernybroe** [comment] 2023-05-11 09:17
I am not able to reproduce it 👀 
![image](https://github.com/pestphp/pest-intellij/assets/5870441/133240c8-1954-40dc-bfef-408393826bef)

```
uses(
    Tests\TestCase::class,
    // Illuminate\Foundation\Testing\RefreshDatabase::class,
)->in('Feature');
```

Running the exact same commands. 


Might be a Windows specific bug perhaps 🤔 Don't have a Windows machine to verify on.

**Comment by scheMeZa** [comment] 2023-05-11 09:28
It probably is specific to Windows.

Is there anything I can do to help from my side?

**Comment by olivernybroe** [comment] 2023-05-13 21:16
Closing this one as a fix in pest should have landed now 👀 try updating pest itself and see if still an issue. 

If it is, I'll reopen 👍

**Comment by olivernybroe** [comment] 2023-05-13 21:18
@scheMeZa if you are up to it you can try and build the plugin locally and run with a debugger to see what happens in the locations I referenced 🙂

**Comment by olivernybroe** [comment] 2023-09-12 06:08
I tried on a Windows machine and I cannot reproduce it. 
Does it still happen for you?

**Closed by olivernybroe** 2023-09-12 06:08 UTC
