### ISSUE TITLE
Suggests createMock Public

### ISSUE THREAD

**Issue by pedroresende** [pestphp/pest-intellij#139] opened 2021-07-21 15:49 UTC
![image](https://user-images.githubusercontent.com/951377/126519335-ff42d3e8-5f4b-4e19-b70e-eb43f429c558.png)

**Comment by olivernybroe** [comment] 2021-07-22 09:52
Hi, thanks for reporting this. 

So the following error is actually caused by something internal in phpstorm that we cannot control. 
We have however together with phpstorm gotten this fixed in the current beta version. 

So if you upgrade your phpstorm to the beta version, this error should disappear

**Closed** 2021-07-22 09:53 UTC
