### ISSUE TITLE
org.picocontainer.defaults.PicoInvocationTargetInitializationException: InvocationTargetException: java.lang.reflect.InvocationTargetException null

### ISSUE THREAD

**Issue by grEvenX** [pestphp/pest-intellij#231] opened 2021-12-03 13:37 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 1.2.2
| Pest version     | x.y.z
| IntelliJ version | PS-213.5744.279
| OS               | Mac OS X

### Description
Got an exception, was not running any tests or anything at the time when this one showed up.
I think it showed up at the same time that a co-worker joined with Code-with-me.

### Stacktrace
```
org.picocontainer.defaults.PicoInvocationTargetInitializationException: InvocationTargetException: java.lang.reflect.InvocationTargetException null
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:112)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:71)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:53)
	at com.jetbrains.rdserver.e.d5.run(d5.java:341)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.resetEditorFrom(PestTestRunConfigurationEditor.kt:70)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.<init>(PestTestRunConfigurationEditor.kt:34)
	at com.pestphp.pest.configuration.PestRunConfiguration.getConfigurationEditor(PestRunConfiguration.kt:54)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.toModel(BackendRunConfigurationsHost.kt:144)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.<init>(BackendRunConfigurationsHost.kt:86)
	at jdk.internal.reflect.GeneratedConstructorAccessor231.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:107)
	... 33 more
Caused by: org.picocontainer.defaults.CyclicDependencyException: Cyclic dependency: [class com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost]
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:67)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:53)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:155)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstanceOfType(DefaultPicoContainer.java:150)
	at com.jetbrains.rdserver.e.dS.F(dS.java:327)
	at com.jetbrains.rdserver.e.dS.invoke(dS.java:92)
	at com.jetbrains.rdserver.RdServerPerClientComponents.tryGetService(RdServerClientDispatcher.kt:71)
	at com.jetbrains.rdserver.RdServerPerClientComponents.getService(RdServerClientDispatcher.kt:78)
	at com.jetbrains.rdserver.RdServerPerClientComponents.access$getService(RdServerClientDispatcher.kt:14)
	at com.jetbrains.rdserver.RdServerPerClientComponents$Companion.getService(RdServerClientDispatcher.kt:29)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost$Companion.getInstance(BackendRunConfigurationsHost.kt:223)
	at com.jetbrains.rdserver.execution.BackendRunManager.getSelectedConfigurationId(BackendRunManager.kt:17)
	at com.intellij.execution.impl.RunManagerImpl.getSelectedConfiguration(RunManagerImpl.kt:559)
	at com.jetbrains.php.run.PhpRunConfigurationInterpreterCombobox.updateItems(PhpRunConfigurationInterpreterCombobox.java:45)
	at com.jetbrains.php.run.PhpRunConfigurationInterpreterCombobox.reset(PhpRunConfigurationInterpreterCombobox.java:40)
	at com.jetbrains.php.run.PhpCommandLineConfigurationEditor.resetEditorFrom(PhpCommandLineConfigurationEditor.java:77)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:50)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:19)
	... 46 more
Caused by:

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.resetEditorFrom(PestTestRunConfigurationEditor.kt:70)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.<init>(PestTestRunConfigurationEditor.kt:34)
	at com.pestphp.pest.configuration.PestRunConfiguration.getConfigurationEditor(PestRunConfiguration.kt:54)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.toModel(BackendRunConfigurationsHost.kt:144)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.<init>(BackendRunConfigurationsHost.kt:86)
	at jdk.internal.reflect.GeneratedConstructorAccessor231.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:107)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:71)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:53)
	at com.jetbrains.rdserver.e.d5.run(d5.java:341)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.picocontainer.defaults.CyclicDependencyException: Cyclic dependency: [class com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost]
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:67)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:53)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:155)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstanceOfType(DefaultPicoContainer.java:150)
	at com.jetbrains.rdserver.e.dS.F(dS.java:327)
	at com.jetbrains.rdserver.e.dS.invoke(dS.java:92)
	at com.jetbrains.rdserver.RdServerPerClientComponents.tryGetService(RdServerClientDispatcher.kt:71)
	at com.jetbrains.rdserver.RdServerPerClientComponents.getService(RdServerClientDispatcher.kt:78)
	at com.jetbrains.rdserver.RdServerPerClientComponents.access$getService(RdServerClientDispatcher.kt:14)
	at com.jetbrains.rdserver.RdServerPerClientComponents$Companion.getService(RdServerClientDispatcher.kt:29)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost$Companion.getInstance(BackendRunConfigurationsHost.kt:223)
	at com.jetbrains.rdserver.execution.BackendRunManager.getSelectedConfigurationId(BackendRunManager.kt:17)
	at com.intellij.execution.impl.RunManagerImpl.getSelectedConfiguration(RunManagerImpl.kt:559)
	at com.jetbrains.php.run.PhpRunConfigurationInterpreterCombobox.updateItems(PhpRunConfigurationInterpreterCombobox.java:45)
	at com.jetbrains.php.run.PhpRunConfigurationInterpreterCombobox.reset(PhpRunConfigurationInterpreterCombobox.java:40)
	at com.jetbrains.php.run.PhpCommandLineConfigurationEditor.resetEditorFrom(PhpCommandLineConfigurationEditor.java:77)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:50)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:19)
	... 46 more
```

**Comment by olivernybroe** [comment] 2021-12-03 13:52
Hi @grEvenX, thanks for reporting this! 

I can see that the stacktrace has been truncated because it was too long, could you attach the full stacktrace (that's the one you see in the window in phpstorm) and copy paste that?

**Comment by grEvenX** [comment] 2021-12-03 23:31
@olivernybroe Updated the description with the paste now 👍

**Comment by olivernybroe** [comment] 2022-05-17 18:32
This was caused by a bug in phpstorm code with me plugin which should have been fixed in later versions. 

If you still experience it, I will reopen and see if we can also workaround it or get phpstorm to work on it.

**Comment by hansnn** [comment] 2022-05-18 10:53
Just got the same exception (or at least very similar) when a co-worker joined a Code With Me session (see stack trace below).

Versions:
PhpStorm 2022.1.1
Plugin version 1.5.0
OS Mac OS X


```
org.picocontainer.defaults.PicoInvocationTargetInitializationException: InvocationTargetException: java.lang.reflect.InvocationTargetException null
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:114)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:73)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:55)
	at com.jetbrains.rdserver.I.u.run(u.java:341)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.resetEditorFrom(PestTestRunConfigurationEditor.kt:70)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.<init>(PestTestRunConfigurationEditor.kt:34)
	at com.pestphp.pest.configuration.PestRunConfiguration.getConfigurationEditor(PestRunConfiguration.kt:51)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.toModel(BackendRunConfigurationsHost.kt:144)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.<init>(BackendRunConfigurationsHost.kt:86)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:109)
	... 35 more
Caused by: org.picocontainer.defaults.CyclicDependencyException: Cyclic dependency: [class com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost]
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:69)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:55)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:155)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstanceOfType(DefaultPicoContainer.java:150)
	at com.jetbrains.rdserver.I.q.j(q.java:327)
	at com.jetbrains.rdserver.I.q.invoke(q.java:92)
	at com.jetbrains.rdserver.RdServerPerClientComponents.tryGetService(RdServerClientDispatcher.kt:71)
	at com.jetbrains.rdserver.RdServerPerClientComponents.getService(RdServerClientDispatcher.kt:78)
	at com.jetbrains.rdserver.RdServerPerClientComponents.access$getService(RdServerClientDispatcher.kt:14)
	at com.jetbrains.rdserver.RdServerPerClientComponents$Companion.getService(RdServerClientDispatcher.kt:29)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost$Companion.getInstance(BackendRunConfigurationsHost.kt:223)
	at com.jetbrains.rdserver.execution.BackendRunManager.getSelectedConfigurationId(BackendRunManager.kt:17)
	at com.intellij.execution.impl.RunManagerImpl.getSelectedConfiguration(RunManagerImpl.kt:575)
	at com.jetbrains.php.run.PhpRunConfigurationInterpreterCombobox.updateItems(PhpRunConfigurationInterpreterCombobox.java:45)
	at com.jetbrains.php.run.PhpRunConfigurationInterpreterCombobox.reset(PhpRunConfigurationInterpreterCombobox.java:40)
	at com.jetbrains.php.run.PhpCommandLineConfigurationEditor.resetEditorFrom(PhpCommandLineConfigurationEditor.java:77)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:50)
	... 49 more
Caused by:

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.resetEditorFrom(PestTestRunConfigurationEditor.kt:70)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.<init>(PestTestRunConfigurationEditor.kt:34)
	at com.pestphp.pest.configuration.PestRunConfiguration.getConfigurationEditor(PestRunConfiguration.kt:51)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.toModel(BackendRunConfigurationsHost.kt:144)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.<init>(BackendRunConfigurationsHost.kt:86)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:109)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:73)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:55)
	at com.jetbrains.rdserver.I.u.run(u.java:341)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: org.picocontainer.defaults.CyclicDependencyException: Cyclic dependency: [class com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost]
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:69)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:55)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:155)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstanceOfType(DefaultPicoContainer.java:150)
	at com.jetbrains.rdserver.I.q.j(q.java:327)
	at com.jetbrains.rdserver.I.q.invoke(q.java:92)
	at com.jetbrains.rdserver.RdServerPerClientComponents.tryGetService(RdServerClientDispatcher.kt:71)
	at com.jetbrains.rdserver.RdServerPerClientComponents.getService(RdServerClientDispatcher.kt:78)
	at com.jetbrains.rdserver.RdServerPerClientComponents.access$getService(RdServerClientDispatcher.kt:14)
	at com.jetbrains.rdserver.RdServerPerClientComponents$Companion.getService(RdServerClientDispatcher.kt:29)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost$Companion.getInstance(BackendRunConfigurationsHost.kt:223)
	at com.jetbrains.rdserver.execution.BackendRunManager.getSelectedConfigurationId(BackendRunManager.kt:17)
	at com.intellij.execution.impl.RunManagerImpl.getSelectedConfiguration(RunManagerImpl.kt:575)
	at com.jetbrains.php.run.PhpRunConfigurationInterpreterCombobox.updateItems(PhpRunConfigurationInterpreterCombobox.java:45)
	at com.jetbrains.php.run.PhpRunConfigurationInterpreterCombobox.reset(PhpRunConfigurationInterpreterCombobox.java:40)
	at com.jetbrains.php.run.PhpCommandLineConfigurationEditor.resetEditorFrom(PhpCommandLineConfigurationEditor.java:77)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:50)
	... 49 more
```

**Comment by olivernybroe** [comment] 2022-05-21 06:19
Thanks for sharing. 
Damn, hoped they had fixed it completely now...

**Comment by olivernybroe** [comment] 2023-02-17 07:46
Reclosing this as it seems like I have no control over this and unfortunately is on IntelliJ's side. 

Thanks for reporting!

**Closed by olivernybroe** 2023-02-17 07:46 UTC
Labels: bug
