### ISSUE TITLE
Tests file fully wrapped in described not being recognised as pest files

### ISSUE THREAD

**Issue by Roboroads** [pestphp/pest-intellij#491] opened 2023-08-17 14:42 UTC
**Describe the bug**
As title: when all yout `it()`s are wrapped in the new `describe()` function, the file is not recognised as pest-file anymore, and stops being testable from the IDE.

**To Reproduce**
1. Create a test file
2. Create a test within a describe.
3. Pest logo does not appear, pest play-icon does not appear either.

Example test:
```php
<?php

describe('something', function () {
    it('verifies true')->expect(true)->toBeTrue();
});
```

**Expected behavior**
The file should be recognised as Pest tests.

**Screenshots**
![image](https://github.com/pestphp/pest-intellij/assets/4398301/b20a4063-02f1-4d9e-9eca-4d85cf8d8e8a)
![image](https://github.com/pestphp/pest-intellij/assets/4398301/50a57d43-7f61-44a9-83ba-4699027c1020)

**Desktop (please complete the following information):**
 - OS: Linux
 - IntelliJ Version: PHPStorm 2023.2
 - Plugin Version: 1.10.1

**Comment by olivernybroe** [comment] 2023-08-17 15:42
Duplicate of #462

**Closed** 2023-08-17 15:42 UTC
