### ISSUE TITLE
Support for running new pest describe blocks inline? 

### ISSUE THREAD

**Issue by evankford** [pestphp/pest-intellij#482] opened 2023-07-25 15:28 UTC
Hey ya'll!

With new describe blocks for pest 2.9, I'm wondering if there's any intention of supporting running them inline with the play button and fixing issues with test inside these blocks not correctly running.

Currently, trying to single out tests inside describe blocks is broken, and there is no option to run the whole block. 

That said, the blocks themselves are obviously being correctly executed at some point, as they run just fine when you test the whole file.

Just wondering what this would take and what the possible pitfalls are here!

**Comment by olivernybroe** [comment] 2023-07-25 16:11
Hey 👋 
We have already outlined all the work needed. However nobody has started on it, but I am welcome to maintaining it in the plugin if you wanna contribute with support for it. (don't use describe block myself)

duplicate of #462

**Closed by olivernybroe** 2023-07-25 16:11 UTC
