### ISSUE TITLE
Rerun failed tests

### ISSUE THREAD

**Issue by adamthehutt** [pestphp/pest-intellij#35] opened 2020-07-24 19:10 UTC
A very handy feature when running phpunit tests in PhpStorm is "rerun failed tests". If you have a large test suite and 1974 out of 2000 pass, it's very handy to be able to automatically rerun the 26 failing tests without having to go through the entire suite. 

It doesn't look like the plugin supports this yet. How hard would this be to implement? I have no experience with PhpStorm plugins, but I'd be happy to help if someone could point me in the right direction.

**Comment by olivernybroe** [comment] 2020-07-25 06:44
Hi, yes this would indeed be an awesome feature.

I haven't tried implementing it myself, but it looks like you would have to overwrite `PestRunConfiguration::createRerunAction`
and return an implementation of `AbstractRerunFailedTestsAction`, which would have the logic needed for rerunning tests.

For running the plugin locally, use the following gradle task `runIde`.

**Comment by olivernybroe** [comment] 2020-07-27 06:09
New discovery for this one. 

The way it finds out which tests are failing is from the output of running pest, however the `teamcity` format is wrong in pest as the locationHint says
```
##teamcity[testStarted name='it lives twice' locationHint='php_qn:///Users/uruloke/Code/dummy-project/vendor/pestphp/pest/src/Factories/TestCaseFactory.php(204) : eval()|'d code::\P\Tests\Unit\ExampleTest::it lives twice' flowId='83891']
```
Which is not something we can use.

For fixing this we have to write a custom `teamcity` printer and add it to pest and then we can implement a `LocationProvider` that understands our format for `locationHint`

**Comment by adamthehutt** [comment] 2020-07-27 18:47
Thank you for looking into this!

**Comment by olivernybroe** [comment] 2020-08-01 09:27
Alright, so this is actually working now, however it requires using the pest branch which adds the new TeamCity format (still waiting to be merged) and the pr of the plugin which adds rerun support (also waiting to be merged).

**Comment by adamthehutt** [comment] 2020-08-02 06:34
Amazing! Thanks so much for tackling this and sorry I wasn't able to help.

**Comment by olivernybroe** [comment] 2020-08-05 06:45
Re-opening this one as we are still waiting for https://github.com/pestphp/pest/issues/140 to be merged.

**Comment by olivernybroe** [comment] 2020-09-16 07:58
@adamthehutt  Could you please update your PestPHP to `^0.3.4` and report back if this works now. It should work 👍

**Comment by adamthehutt** [comment] 2020-09-16 21:57
I'm getting a fatal IDE error: 

```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.pestphp.pest.configuration.PestLocationProvider.getLocation(PestLocationProvider.kt:79)
	at com.pestphp.pest.configuration.PestLocationProvider.findElement(PestLocationProvider.kt:60)
	at com.pestphp.pest.configuration.PestLocationProvider.getLocation(PestLocationProvider.kt:31)
	at com.intellij.execution.testframework.sm.runner.SMTestLocator.getLocation(SMTestLocator.java:50)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$CombinedTestLocator.getLocation(SMTestRunnerConnectionUtil.java:243)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.lambda$computeLocation$2(SMTestProxy.java:293)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.java:353)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.computeLocation(SMTestProxy.java:292)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.lambda$getLocation$0(SMTestProxy.java:275)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.getLocation(SMTestProxy.java:279)
	at com.pestphp.pest.configuration.PestRerunFailedTestsAction$getRunProfile$1.getState(PestRerunFailedTestsAction.kt:44)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:207)
	at com.intellij.execution.runners.DefaultRunProgramRunner.execute(DefaultRunProgramRunner.kt:17)
	at com.intellij.execution.testframework.actions.AbstractRerunFailedTestsAction.performAction(AbstractRerunFailedTestsAction.java:201)
	at com.intellij.execution.testframework.actions.AbstractRerunFailedTestsAction.execute(AbstractRerunFailedTestsAction.java:150)
	at com.intellij.execution.testframework.actions.AbstractRerunFailedTestsAction.actionPerformed(AbstractRerunFailedTestsAction.java:137)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:276)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:155)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:439)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by olivernybroe** [comment] 2020-09-17 06:22
@adamthehutt Thanks for testing it out, having some troubles replicating. Could you share your test file?

**Comment by olivernybroe** [comment] 2020-09-17 06:35
Ah nvm. I see the error. Small stupid mistake 👍

**Comment by olivernybroe** [comment] 2020-09-17 06:54
I released a new alpha version, could you test if it fixes it for you https://github.com/pestphp/pest-intellij/releases/tag/v0.4.0-alpha.6 ?

**Comment by adamthehutt** [comment] 2020-09-17 23:42
@olivernybroe It no longer errors, but now it re-runs all the tests from the last run, not just the failing ones.

**Comment by olivernybroe** [comment] 2020-09-18 07:13
@adamthehutt Hmm interesting. I'll see if I can reproduce. Thanks for testing out.

Will return when I have a new version for testing out.

**Comment by olivernybroe** [comment] 2020-09-18 10:01
![rerun test](https://user-images.githubusercontent.com/5870441/93584913-4b36ee80-f9a6-11ea-93ef-2d18f032a447.gif)
I haven't been able to reproduce.

Could you share some more information?
Could be nice with some test where this is happening for you.

**Comment by olivernybroe** [comment] 2020-09-18 10:04
Ah do you have phpunit tests also in your testsuite? 

I just tested it out with a failing phpunit test and was not able to rerun that one alone.

**Comment by adamthehutt** [comment] 2020-09-18 19:18
Yes, I do have a mix of legacy phpunit tests and pest tests. When I run only phpunit tests, that test runner is able to do this correctly (re-run only the failing tests). But when I use the pest runner, clicking that button reruns all tests from the previous run. This is the case whether the run included phpunit and pest tests or just pest tests.

Here's a simple example:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/57567/93636397-91348800-f98f-11ea-90fe-ec2cb7aef99f.gif)

**Comment by adamthehutt** [comment] 2020-09-18 19:42
Just thinking about what might be different between your setup and mine... Any chance the settings in phpunit.xml could influence this?

**Comment by olivernybroe** [comment] 2020-09-18 23:05
Hmm do you have the newest version of pest in your composer? We had to do some changes in the php code for this to work, so the newest pest version is required, not only the newest plugin version.

In my example In just have the default Laravel

**Comment by adamthehutt** [comment] 2020-09-19 00:29
Composer shows pest 0.3.5, which I think is the newest version.

It's true that I'm doing this in a mature application with a ton of tests, code, etc. However, I just tested again in a very bare-bones project (not even a full laravel app, just a few files), and the same thing happens. :(

**Comment by olivernybroe** [comment] 2020-09-19 08:01
@adamthehutt Ah, just looked closely at your test case, I think I see the issue.

It cannot select the test because they are in a namespace. Can you make a quick tests to see if it works for you without the namespace, meanwhile I'll work on a fix for making it work with namespaces 👍 (It broke because of some speed optimisations we did for finding pest tests)

**Comment by olivernybroe** [comment] 2020-09-19 08:58
Third times the charm. Could you test out with this version?
https://github.com/pestphp/pest-intellij/releases/tag/v0.4.0-alpha.7

**Comment by adamthehutt** [comment] 2020-09-21 17:36
@olivernybroe We're getting closer! Still doesn't work, but I think I can give you some useful feedback. A few bits of hopefully helpful information:

1. When my tests use it(), the "rerun" feature never works. It always reruns every test from the prior run. However, when they use test(), it *does* rerun a subset of the previous run.

2. When a test() test fails, if I click the rerun failed tests button, it reruns the test that failed, but it is also picking up other tests that weren't even run in the latest attempt. My best guess is that this is a regex issue or something along those lines. Here's what's happening:

### FileA:
```
test ('passes', function () {
    expect(true)->toBeTrue();
});

test ('fails', function () {
    expect(false)->toBeTrue();
});
```
I run pest for FileA, and the predictable happens - one pass and one fail. Then I click rerun failed tests, and the following strange behavior occurs.

It reruns the failed test, but it also runs a test from FileB that is totally unrelated (not even in the same directory and not even a Pest test!):

### FileB (different directory, not included in original run)
```
class BlahBlahTest extends TestCase 
{
    /** @test **/
    public function does_something_something_if_something_fails() 
    {
        ... 
    }
}
```

The reason I'm suggesting it could be a regex issue is that the end of this test's method name is "fails", which is the same as the name of the failing Pest test.

**Comment by olivernybroe** [comment] 2020-09-22 06:18
@adamthehutt Thanks for the detailed information. This makes is soo much easier for me to try and solve.

I'll make the regex a lot tighter, realised that the regex I use for rerunning and for running a single test was not the same 🤦 
Will write when I have a patch ready with fixes for this.

**Comment by olivernybroe** [comment] 2020-09-29 07:04
Alright :) Sorry to keep bugging you with testing it out, but could you see if this version fixes it?

I have improved the regex, so it is tightly bound and found some code that should fix the `it` problem also.

[pest-intellij-0.4.1-alpha.1.zip](https://github.com/pestphp/pest-intellij/files/5297040/pest-intellij-0.4.1-alpha.1.zip)

**Comment by adamthehutt** [comment] 2020-10-01 02:09
Hey, sorry for the slow reply @olivernybroe. I'm honestly not sure how to install the plugin from a zip file instead of the marketplace. Will the update show up there or do you need me to test first?

**Comment by olivernybroe** [comment] 2020-10-01 05:03
@adamthehutt this time I'll wait publishing it until we know it works :) it will prompt you to update like normal (with marketplace) even when you install an update manually. 

The way you install manually is 
Preferences > Plugins > ⚙️ > Install plugin from disk...
And then target the zip file, don't unpack it.

**Comment by adamthehutt** [comment] 2020-10-01 19:08
Victory! As far as I can tell, this solves the problem and it's working correctly now. Thanks so much for sticking with this one; it's a really useful feature.

**Comment by olivernybroe** [comment] 2020-10-01 20:44
@adamthehutt Awesome! Thanks for taking the time to test it out for me :) 

I'll create the pr and make a new release soon with it! Then we just need rerunning support for phpunit tests also

**Closed** 2020-10-02 06:13 UTC
Labels: enhancement
