### ISSUE TITLE
PhpStorm Autocomplete not working in closures

### ISSUE THREAD

**Issue by scheMeZa** [pestphp/pest-intellij#331] opened 2022-06-08 09:14 UTC
The biggest hurdle preventing me from using PEST everywhere is that PhpStorm doesn't seem to know what `$this` is inside pest test closures.

Is this an issue with my configuration?

Check:
![image](https://user-images.githubusercontent.com/7773361/172579226-946b6131-6e95-41f5-98c4-d632ddb4a52a.png)

Because of the issue, I cannot autocomplete assertions on responses either.
![image](https://user-images.githubusercontent.com/7773361/172579367-26554ed7-0349-480e-8df6-450944895304.png)

**Comment by scheMeZa** [comment] 2022-06-08 09:18
Just want to add, I do have the plugin installed, and updated this morning:

![image](https://user-images.githubusercontent.com/7773361/172580654-f3337989-c2d1-4f2d-9069-17d2d65b05ee.png)

**Comment by olivernybroe** [comment] 2022-06-08 11:58
Thanks for reporting this. 
This is a feature we already support, could you share your folder structure or a demo project where I can reproduce?

**Comment by scheMeZa** [comment] 2022-06-08 13:45
Here you go:
1. I created a new laravel project to test this out:
https://gitlab.com/jadonbrown/pest-test

2. I installed Pest following the documentation on https://pestphp.com/docs/installation

3. I created a command using `php artisan make:test --pest ExamplePestTest`. 
This created `tests/Feature/ExamplePestTest.php`.

4. I've got the Pest plugin enabled.
![image](https://user-images.githubusercontent.com/7773361/172632059-f4db41d2-80bf-4280-a5e9-522a63ce718f.png)

5. I'm still not getting autocomplete features in the Pest test.
![image](https://user-images.githubusercontent.com/7773361/172632234-942fb8d5-ebd4-42e9-9feb-c4f81fd80082.png)
![image](https://user-images.githubusercontent.com/7773361/172632320-7c1287ae-6b45-4782-9cd4-50fea6cd2ff9.png)

**Comment by scheMeZa** [comment] 2022-06-23 19:20
Is there maybe a workaround for this issue?

**Comment by olivernybroe** [comment] 2022-06-23 19:27
@scheMeZa thank you for providing an example.
No idea if there is a workaround, I haven't looked into it yet.

**Comment by olivernybroe** [comment] 2022-06-30 05:47
@scheMeZa I have cloned your repository and tried out locally and this is what happens for me.
![image](https://user-images.githubusercontent.com/5870441/176601932-09900dab-31c2-47f8-8a64-afe421c233be.png)

**Comment by olivernybroe** [comment] 2022-06-30 06:06
So this means there is something in your setup interfering here 🤔 

I can see you have a lot of plugins installed, a thing we could try is if you disable all the plugins installed from marketplace and only have pest plugin installed. Is it then working? 👀 (we will enable again, just need to figure out if we can isolate the issue)

**Comment by ostark** [comment] 2022-07-26 23:14
I noticed the same when using `uses(class)->in(__DIR__)`.

`uses(class)->in('./')` fixed it for me.

**Comment by olivernybroe** [comment] 2022-07-30 23:17
@ostark what version are you running? I am pretty sure we did add support for `__dir__` already 🤔

**Comment by scheMeZa** [comment] 2022-07-31 08:04
> 

That worked for me, thank you :)

I had mine set to:
`uses(TestCase::class)->in('./Features');`
`uses(TestCase::class)->in('./Unit');`

Switching to
`uses(TestCase::class)->in('./');` fixed IntelliSense for me.

**Comment by olivernybroe** [comment] 2022-08-19 06:55
I am completely unable to reproduce this on v1.8.0. 

Closing as it seems like you found a solution anyways.

**Closed by olivernybroe** 2022-08-19 06:55 UTC
Labels: bug

**Comment by Sans84** [comment] 2023-09-25 20:27
It doesn't work for me.
Steps:
1. Create a new Laravel project
2. Added Pest according to the installation guide
3. Installed the Pest plugin for PCPStorm
4. Created a test

The result is that the autocomplete for closures does not work

5. Disabled all installed plugins except Pest.

It does not work.

6. Make the changes as described above: `uses(TestCase::class)->in('./');`

It does not work
