### ISSUE TITLE
Can't rerun or debug a test

### ISSUE THREAD

**Issue by mathieutu** [pestphp/pest-intellij#494] opened 2023-08-26 09:48 UTC
Hi !

Thank you for your great work !

Usually we can rerun a test or run it in debug mode from the tests results.

With PestPHP, we only can do that with the whole file:

<img width="376" alt="Screenshot 2023-08-26 at 11 44 41" src="https://github.com/pestphp/pest-intellij/assets/11351322/e3e3d103-9996-4bdb-827a-3b4fa3e199ad">
<img width="418" alt="Screenshot 2023-08-26 at 11 44 57" src="https://github.com/pestphp/pest-intellij/assets/11351322/38525da8-2924-4830-85dd-624b46e3f9ac">

Also, we should be able to jump to code by double clicking.

Thanks!

**To Reproduce**
1. Run a test.
2. Context menu on it.
3. "Nothing here"

**Expected behavior**
It should have the same menu than for the file.

**Desktop (please complete the following information):**
 - OS: MacOS 13.4.1 
 - IntelliJ Version: 2023.2.1 RC
 - Plugin Version 1.10.1

**Comment by olivernybroe** [comment] 2023-08-26 12:33
Duplicate of #471

**Closed by olivernybroe** 2023-08-26 12:33 UTC
