### ISSUE TITLE
Invalid configuration

### ISSUE THREAD

**Issue by Lukasss93** [pestphp/pest-intellij#257] opened 2022-03-27 18:08 UTC
**Plugin version:** 1.4.0
**IDE:** PhpStorm 2021.3.3
**OS:** Windows 11

**Description:**
Run/Debug configuration doesn't work anymore after upgrading Pest plugin to the latest version.

**Screenshot:**
![immagine](https://user-images.githubusercontent.com/4071613/160294628-570047aa-2e15-4b62-841a-93cf04ad1fec.png)

**Comment by olivernybroe** [comment] 2022-03-27 19:05
🙈

Could you please share a screenshot of your pest configuration under test frameworks? 👀

**Comment by Lukasss93** [comment] 2022-03-27 19:10
![immagine](https://user-images.githubusercontent.com/4071613/160296822-e4451d18-00e6-4095-8fab-792406fbd6d1.png)

**Comment by Lukasss93** [comment] 2022-03-28 21:41
Temporary fixed downgrading the plugin version to 1.3.0.
Waiting for a permanent fix 😊

**Comment by Sergej-Tihonov** [comment] 2022-03-28 23:15
Same problem with the 'working directory' after update to 1.4.0 here.
Downgrade to 1.3.0 fix the problem.

**Comment by olivernybroe** [comment] 2022-03-29 05:09
Thanks, sorry for the inconvenience. 
Having a bit of trouble reproducing 👀

@Sergej-Tihonov could you confirm if your settings are identical to @Lukasss93?

**Comment by MrSapog** [comment] 2022-03-29 07:41
Have same issue

![Screenshot_1](https://user-images.githubusercontent.com/76447253/160558836-c980c32a-ab70-47ac-b0ba-94930739550c.jpg)

if i set custom directory to "/tests", got another error

![Screenshot_2](https://user-images.githubusercontent.com/76447253/160559539-eecf2f7b-4fba-430e-a285-8ad90f72c670.jpg)

**Comment by olivernybroe** [comment] 2022-03-29 08:03
What version of IntelliJ? And are all of you on windows?

**Comment by MrSapog** [comment] 2022-03-29 08:07
> What version of IntelliJ? And are all of you on windows?

Windows 10 corporate ltsc
PhpStorm 2021.3.3 Build #PS-213.7172.28, built on March 17, 2022

**Comment by MrSapog** [comment] 2022-03-29 08:09
Downgrade to 1.3.0 fixed the problem for me too

**Comment by olivernybroe** [comment] 2022-03-29 08:30
I think I might have found the issue, could you please try out this EAP build and check if it fixes the problems for you?

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-1.4.1-EAP.3.zip](https://github.com/pestphp/pest-intellij/files/8369490/PEST.PHP-1.4.1-EAP.3.zip)

**Comment by Sergej-Tihonov** [comment] 2022-03-29 08:41
@olivernybroe tested your provided version "PEST PHP-1.4.1-EAP.3.zip". Works for me like a charm. Thank you very much for the fix.
Details to my System:
- MacOS (M1)
- PhpStorm 2021.3.3
- I run my project in a docker container via remote interpreter

**Comment by olivernybroe** [comment] 2022-03-29 08:43
@Sergej-Tihonov Thank you for testing it! ❤️ 
Interesting that you also had the issue on M1, the issue was related to me making the stupid mistake of assuming `/` as path separator... 


Will wait for @Lukasss93  or @MrSapog to also test it before I will begin the process or releasing it as a stable version.

**Comment by MrSapog** [comment] 2022-03-29 08:58
@olivernybroe works for me too. Wow thats the speed! Thanks a lot!

**Comment by olivernybroe** [comment] 2022-03-29 09:02
Thanks for being fast testing it, I'll begin the release process. Might take up to a day for them to review.

Closing this issue 👍

**Closed by olivernybroe** 2022-03-29 09:02 UTC
Labels: bug
