### ISSUE TITLE
Running Tests in parallel using the `--parallel` pest option

### ISSUE THREAD

**Issue by keith-ferney** [pestphp/pest-intellij#487] opened 2023-08-09 22:50 UTC
When I add the `--parallel` to the `Test Runner Options` field in my Run/Debug Configurations the test run does not behave as expected

it currently does not recognize that the tests are running in parallel, it only shows the command output, not the list of tests and the statuses

**Comment by olivernybroe** [comment] 2023-08-10 04:08
Duplicate of #375

**Closed by olivernybroe** 2023-08-10 04:08 UTC
