### ISSUE TITLE
Exception when used together with Code with me

### ISSUE THREAD

**Issue by nikcani** [pestphp/pest-intellij#121] opened 2021-05-03 19:01 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 0.4.3
| Pest version     | 0.3.19
| IntelliJ version | PS-211.7036.8
| OS               | Mac OS X

### Description
I started a code with me session.

### Stacktrace
```
org.picocontainer.defaults.PicoInvocationTargetInitializationException: InvocationTargetException: java.lang.reflect.InvocationTargetException null
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:112)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:71)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:53)
	at com.jetbrains.rdserver.b.k.a(k.java:314)
	at com.jetbrains.rdserver.b.k.invoke(k.java:84)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:27)
	at com.jetbrains.rdserver.b.aQ.a(aQ.java:273)
	at com.jetbrains.rdserver.b.aQ.a(aQ.java:235)
	at com.jetbrains.rdserver.b.aQ.a(aQ.java:84)
	at com.jetbrains.rdserver.b.m.run(m.java:611)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.Applic
```

**Comment by olivernybroe** [comment] 2021-05-04 06:09
Thanks for reporting this!

Seems like it doesn't contain the full stacktrace, as the stacktrace was too long for get parameters...
Would you be able to get me the full stacktrace? 
The part of the stacktrace I have here contains no lines of code which is related to pest unfortunately.

**Comment by olivernybroe** [comment] 2021-05-11 21:00
Closing this for now. Just had a code with me session and no errors occured 🙂

Will reopen if it happens again for you or anybody else. 
Hopefully we have the full stack trace then, so we can see where it went wrong.

**Comment by nikcani** [comment] 2021-05-21 11:02
i ran into the issue again, here is the full stacktrace that is shown in my ide

```
org.picocontainer.defaults.PicoInvocationTargetInitializationException: InvocationTargetException: java.lang.reflect.InvocationTargetException null
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:112)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:71)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:53)
	at com.jetbrains.rdserver.a.Q.a(Q.java:323)
	at com.jetbrains.rdserver.a.Q.invoke(Q.java:87)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:27)
	at com.jetbrains.rdserver.a.au.a(au.java:282)
	at com.jetbrains.rdserver.a.au.a(au.java:238)
	at com.jetbrains.rdserver.a.au.a(au.java:87)
	at com.jetbrains.rdserver.a.al.run(al.java:620)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.resetEditorFrom(PestTestRunConfigurationEditor.kt:68)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.<init>(PestTestRunConfigurationEditor.kt:32)
	at com.pestphp.pest.configuration.PestRunConfiguration.getConfigurationEditor(PestRunConfiguration.kt:54)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.toModel(BackendRunConfigurationsHost.kt:99)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.<init>(BackendRunConfigurationsHost.kt:80)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:107)
	... 40 more
Caused by: com.intellij.openapi.editor.ReadOnlyModificationException: Attempt to modify read-only document: guardClass=com.jetbrains.rdserver.permissions.impl.BackendDocumentWriteAccessGuard, failureReason=The client (keanu) has no write access at all. The file bound to document is (class=LightVirtualFile name=Dummy.txt)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertWriteAccess(DocumentImpl.java:704)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:605)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:597)
	at com.intellij.ui.EditorTextField.lambda$setText$1(EditorTextField.java:283)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959)
	at com.intellij.ui.EditorTextField.lambda$setText$2(EditorTextField.java:277)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.ui.EditorTextField.setText(EditorTextField.java:276)
	at com.jetbrains.php.testFramework.run.PhpTestRunnerConfigurationEditor.resetEditorFrom(PhpTestRunnerConfigurationEditor.java:262)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:49)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:19)
	... 54 more
Caused by:

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.resetEditorFrom(PestTestRunConfigurationEditor.kt:68)
	at com.pestphp.pest.configuration.PestTestRunConfigurationEditor.<init>(PestTestRunConfigurationEditor.kt:32)
	at com.pestphp.pest.configuration.PestRunConfiguration.getConfigurationEditor(PestRunConfiguration.kt:54)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.toModel(BackendRunConfigurationsHost.kt:99)
	at com.jetbrains.rdserver.execution.configurations.BackendRunConfigurationsHost.<init>(BackendRunConfigurationsHost.kt:80)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:107)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:71)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:53)
	at com.jetbrains.rdserver.a.Q.a(Q.java:323)
	at com.jetbrains.rdserver.a.Q.invoke(Q.java:87)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:27)
	at com.jetbrains.rdserver.a.au.a(au.java:282)
	at com.jetbrains.rdserver.a.au.a(au.java:238)
	at com.jetbrains.rdserver.a.au.a(au.java:87)
	at com.jetbrains.rdserver.a.al.run(al.java:620)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.openapi.editor.ReadOnlyModificationException: Attempt to modify read-only document: guardClass=com.jetbrains.rdserver.permissions.impl.BackendDocumentWriteAccessGuard, failureReason=The client (keanu) has no write access at all. The file bound to document is (class=LightVirtualFile name=Dummy.txt)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertWriteAccess(DocumentImpl.java:704)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:605)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:597)
	at com.intellij.ui.EditorTextField.lambda$setText$1(EditorTextField.java:283)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959)
	at com.intellij.ui.EditorTextField.lambda$setText$2(EditorTextField.java:277)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.ui.EditorTextField.setText(EditorTextField.java:276)
	at com.jetbrains.php.testFramework.run.PhpTestRunnerConfigurationEditor.resetEditorFrom(PhpTestRunnerConfigurationEditor.java:262)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:49)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfigurationEditor.resetEditorFrom(PhpTestRunConfigurationEditor.java:19)
	... 54 more
```

**Comment by olivernybroe** [comment] 2021-07-26 07:00
I think I might have figured out what went wrong. It seems like the issue was caused by the participant only having read access and tried to do some modifications to the test runner which requires write access. 

I have a fix ready for the next EAP.
[PEST PHP-0.4.4-EAP.4.zip](https://github.com/pestphp/pest-intellij/files/6876226/PEST.PHP-0.4.4-EAP.4.zip)

**Closed** 2021-07-26 12:34 UTC
Labels: bug
