### ISSUE TITLE
Exception happens in ThisTypeProvider

### ISSUE THREAD

**Issue by marcandreappel** [pestphp/pest-intellij#98] opened 2021-02-12 11:27 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 0.4.2
| Pest version     | x.y.z
| OS               | Linux

### Stacktrace
```
com.intellij.diagnostic.PluginException: TypeProvider contract violation? by class com.pestphp.pest.types.ThisTypeProvider on test('example', function () {
    expect(true)->toBeTrue();
}) [Plugin: com.pestphp.pest-intellij]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:300)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:81)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.lambda$getTypeFromAST$1(PhpTypeInfo.java:93)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getTypeFromAST(PhpTypeInfo.java:74)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:57)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:31)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:238)
	at com.jetbrains.php.lang.psi.elements.PhpTypedElement.getGlobalType(PhpTypedElement.java:53)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:50)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpFunctionCall(PhpVoidFunctionResultUsedInspection.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl.accept(FunctionReferenceImpl.java:50)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:309)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:275)
	at com.intellij.codeInspection.ex.InspectionEventsKt.reportWhenInspectionFinished(inspectionEvents.kt:9)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:270)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:266)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAnd
```

**Comment by olivernybroe** [comment] 2021-02-12 11:58
Thanks for reporting this. Could you share the code which caused the issue and what happens? 

Is something not working or is this error just thrown in the background?

**Comment by divspace** [comment] 2021-02-13 00:23
Same issue for me. Here's the report (same stacktrace):

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Plugin version   | 0.4.2
| Pest version     | x.y.z
| OS               | Mac OS X

Here's the code (brand new test):

```php
<?php

it('scrapes a website', function () {
    $response = $this->get('/panther');

    $response->assertStatus(200);
});
```

This happens immediately on start (it's the file I have open). If I restart it pops the error up and I have to disable the plugin.

**Comment by olivernybroe** [comment] 2021-02-14 07:41
@divspace thanks for the additional information, we will try and reproduce it 👍 

@adelf Do you know what is wrong with the type provider?

**Comment by adelf** [comment] 2021-02-14 07:54
PhpStorm version? @olivernybroe you should add it to the table in the bug template.

**Comment by olivernybroe** [comment] 2021-02-14 07:58
@adelf huh, yeah good idea. I'll create an issue for it so I don't forget 👍

**Comment by olivernybroe** [comment] 2021-07-26 07:03
@marcandreappel, @divspace so some changes has happened since this version and I am having some troubles reproducing, is this still happening for you?

**Comment by olivernybroe** [comment] 2021-08-03 09:58
Closing until further info 👍

**Closed by olivernybroe** 2021-08-03 09:58 UTC
Labels: bug
