### ISSUE TITLE
Navigating to test from test result is not working

### ISSUE THREAD

**Issue by lloricode** [pestphp/pest-intellij#205] opened 2021-10-26 15:01 UTC
Hi @olivernybroe 

came from tweet: https://twitter.com/OliverNybroe/status/1453007653609906195?s=20

https://nimb.ws/fcnZmL

This is detail of my IDE:

```
PhpStorm 2021.2.3
Build #PS-212.5457.49, built on October 13, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-89-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.alayouni.ansiHighlight (1.2.4), carbon-now-sh (1.3.0), Key Promoter X (2021.2), zielu.gittoolbox (212.7.15), com.intellij.ideolog (203.0.27.0), String Manipulation (8.20.203.000.1), com.fwdekker.randomness (2.7.3), com.github.syuchan1005.emojiprefix (2.2.1), net.seesharpsoft.intellij.plugins.csv (2.18.0), com.mallowigi (50.0.1), com.your.company.unique.plugin.id (1.0), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), ru.adelf.idea.dotenv (2021.3.0.212), de.beyondco.tinkerwell.tinkerwell (2.0), de.espend.idea.laravel (0.15.4), de.espend.idea.php.annotation (8.0.0), com.pestphp.pest-intellij (1.2.1), dev.nybroe.collector (0.3.5), de.espend.idea.php.phpunit (6.2), com.laravel_idea.plugin (4.4.2.212), com.wakatime.intellij.plugin (13.1.1)
Current Desktop: X-Cinnamon
``

Thank you

**Comment by olivernybroe** [comment] 2021-11-01 13:16
@lloricode Thanks for reporting this, could you please share the test with me, as navigation is working for me, so might be an edgecase in that test which is not working.

**Comment by lloricode** [comment] 2021-11-02 06:15
Hi @olivernybroe will send here thank you

**Comment by lloricode** [comment] 2021-11-18 05:58
hi @olivernybroe sorry for the long wait, will reopen this and give all the details, thank you

**Comment by olivernybroe** [comment] 2021-11-18 06:48
@lloricode awesome 👍 

Just cleaning up in issues that I cannot do anything about. 
But nice, when you have the details I'll reopen and try to reproduce again 🙂

**Comment by lloricode** [comment] 2021-12-04 16:05
> @lloricode Thanks for reporting this, could you please share the test with me, as navigation is working for me, so might be an edgecase in that test which is not working.

Hi @olivernybroe 

thank you for the waiting, and now i been converted PHPunit to Pest this project [this project](https://github.com/lloricode/lumen-boilerplate/tree/main/tests), can you try this one?

and also all our project is same as result, not experiencing as expected as yours

thank you

**Comment by lloricode** [comment] 2021-12-04 16:16
here is a video [link](https://drive.google.com/file/d/1VO1gxZhxdIKBVc0iPqP6FrBz3HxxWbFE/view?usp=sharing)

**Comment by olivernybroe** [comment] 2021-12-05 09:38
@lloricode Ah alright, I think I know what is happening. 
Could you try to see if goto navigation works if it's not a dataset test? 

It seems like goto navigation is not working with datasets.

**Comment by lloricode** [comment] 2021-12-05 09:42
> @lloricode Ah alright, I think I know what is happening. Could you try to see if goto navigation works if it's not a dataset test?
> 
> It seems like goto navigation is not working with datasets.

yes, wait a seconds :eye:

**Comment by lloricode** [comment] 2021-12-05 09:49
still not working in dataset, also i'm not experiencing any navigation work, so I thought it is not implemented yet

**Comment by olivernybroe** [comment] 2021-12-05 10:29
@lloricode Alright, I'll try and clone down your project and see if it works for me 👍

**Comment by olivernybroe** [comment] 2021-12-05 10:35
@lloricode I am simply not able to reproduce it. 

Here is an example of your repository cloned and I am able to navigate the tests, you can also see that I am not able to navigate the dataset tests, as that feature does not work.
https://user-images.githubusercontent.com/5870441/144742985-64d00623-565e-4db6-bcdf-d709ef804472.mp4

**Comment by lloricode** [comment] 2021-12-05 10:58
hmm is there need something to install on my OS? im using linuxmint

**Comment by olivernybroe** [comment] 2021-12-05 12:04
Should be OS agnostic 🤔

Unfortunately I don't have a linux mint to test it out on.

**Comment by lloricode** [comment] 2021-12-05 12:09
is there a way to test it virtually?

**Comment by lloricode** [comment] 2021-12-07 06:54
hi @olivernybroe , i just notice this, 

this is the only work
https://nimb.ws/rgsDvm

its just right click, but double click nothing happen

**Comment by lloricode** [comment] 2021-12-07 06:57
> @lloricode I am simply not able to reproduce it.
> 
> Here is an example of your repository cloned and I am able to navigate the tests, you can also see that I am not able to navigate the dataset tests, as that feature does not work. https://user-images.githubusercontent.com/5870441/144742985-64d00623-565e-4db6-bcdf-d709ef804472.mp4

I'm excited about your example, :heart: but sadly does not work in mine :cry: 
![Screenshot from 2021-12-07 14-55-23](https://user-images.githubusercontent.com/8251344/144981253-9764ca0b-e097-4e18-a873-8bc1d1504ca3.png)

**Comment by olivernybroe** [comment] 2021-12-07 09:24
@lloricode Hmm, alright, so as I am having a lot of trouble reproducing, would you be up to do a pair session, so we can test it out on your setup together and possibly figure out what is wrong? 🤔 

You can hit me up on the pest discord, so we can figure something out
https://github.com/pestphp/pest

**Comment by lloricode** [comment] 2021-12-08 05:17
Yes, will notify you on discord :100:

**Comment by olivernybroe** [comment] 2022-05-17 18:35
Closing this as no follow up has happened yet. 

If needed and when we know more, I'll reopen.

**Comment by milewski** [comment] 2022-07-11 05:53
This has never worked for me since the day one I started using Pest.... I suspect this happens because my setup is pest via remote-interpreter in a docker container... can you confirm this works for you? if so what is the secret...

**Comment by olivernybroe** [comment] 2022-07-11 07:03
@milewski Found the issue and I have made a new EAP. 

Would you be able to test it out and see if it solves the issue for you? 
[PEST PHP-1.8.0-EAP.1.zip](https://github.com/pestphp/pest-intellij/files/9081579/PEST.PHP-1.8.0-EAP.1.zip)

Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>

**Comment by milewski** [comment] 2022-07-11 07:55
@olivernybroe Awesome! it worked!

**Comment by lloricode** [comment] 2022-07-11 07:58
> @olivernybroe Awesome! it worked!

<3

**Comment by lloricode** [comment] 2022-07-11 07:58
> @milewski Found the issue and I have made a new EAP.
> 
> Would you be able to test it out and see if it solves the issue for you? [PEST PHP-1.8.0-EAP.1.zip](https://github.com/pestphp/pest-intellij/files/9081579/PEST.PHP-1.8.0-EAP.1.zip)
> 
> Install it manually using Preferences > Plugins > gear > Install plugin from disk...

ok will try this,

**Comment by lloricode** [comment] 2022-07-11 08:03
> @milewski Found the issue and I have made a new EAP.
> 
> Would you be able to test it out and see if it solves the issue for you? [PEST PHP-1.8.0-EAP.1.zip](https://github.com/pestphp/pest-intellij/files/9081579/PEST.PHP-1.8.0-EAP.1.zip)
> 
> Install it manually using Preferences > Plugins > gear > Install plugin from disk...

it works! thanks @milewski after a 10months now i feel the pest plugin in phpstorm IDE,
also, im using homestead for developing laravel projects, that why is not working on mine

thank you @olivernybroe

**Comment by lloricode** [comment] 2022-07-11 08:04
@olivernybroe will wait for the stable release for this,
thank you :heart_eyes:

**Comment by lloricode** [comment] 2022-07-11 08:23
hi @olivernybroe 

when having dataset, is not working on mine

![Screenshot from 2022-07-11 16-23-17](https://user-images.githubusercontent.com/8251344/178220835-5f1401e4-c940-479a-82fc-5fbcd6cc8c7f.png)
![Screenshot from 2022-07-11 16-23-00](https://user-images.githubusercontent.com/8251344/178220841-dfd3b547-5028-41b0-9a32-72b0cbf36781.png)
![Screenshot from 2022-07-11 16-22-50](https://user-images.githubusercontent.com/8251344/178220846-3e24b2b0-3c53-453c-be76-5987d5d02753.png)


https://nimb.ws/YXThzZ

**Comment by lloricode** [comment] 2022-07-11 08:27
fix show pest pop up on video https://nimb.ws/noAIYe

**Comment by olivernybroe** [comment] 2022-07-11 10:02
Yes, I unfortunately haven't build support for dataset navigation yet. However the navigation works on the file above it 👍 

Basically to make dataset navigation work we need to do changes here
https://github.com/pestphp/pest-intellij/blob/main/src/main/kotlin/com/pestphp/pest/configuration/PestLocationProvider.kt#L79

We either need to loosen the match so the test name `it with dataset` is matched even though the test name is `it with dataset with (1)`. 
Just haven't figured out the best way for doing it, as cutting everything before with could result in references to the wrong test.
Another solution would be that the `locationHint` in the output from pest itself does not include the dataset.


Also thanks for testing it out both of you.

**Comment by olivernybroe** [comment] 2022-08-19 06:47
Closing this as the original issue has been solved, and a separate one for dataset navigation has been opened. #357

**Closed by olivernybroe** 2022-08-19 06:47 UTC
Labels: bug

**Comment by sergyu91ma** [comment] 2023-11-18 22:46
I also have this problem of navigating with double click on the tests. 
My ENV:
PS-232.10072.32, JRE 17.0.8.1+7-b1000.32x64 JetBrains s.r.o., OS Windows 11(amd64) v10.0 , screens 2560.0x1440.0, 2560.0x1440.0

![image](https://github.com/JetBrains/pest-intellij/assets/6949205/bfa3595d-d94e-4c17-aabb-12067c04a827)

![image](https://github.com/JetBrains/pest-intellij/assets/6949205/fdb22834-25d3-4a10-8660-e63eadea6c88)

**Comment by olivernybroe** [comment] 2023-11-19 08:17
@sergyu91ma please report the issue at YouTrack, as we don't collect issues anymore on GitHub.
https://youtrack.jetbrains.com/newIssue?project=WI&draftId=25-4942628

**Comment by sergyu91ma** [comment] 2023-11-19 08:30
i did: 
https://youtrack.jetbrains.com/issue/JT-78295/Navigating-to-test-from-test-result-is-not-working
