### ISSUE TITLE
Can't run test in a describe block

### ISSUE THREAD

**Issue by riiad** [pestphp/pest-intellij#481] opened 2023-07-21 09:15 UTC
Hi,

I just updated to Pest 2.9 which adds `describe` blocks among other things.
It seems that the `--filter` option is not working well with this new `describe` block, when i run a test inside a `describe` block i get an error (see screenshot).

1. Write a test inside a `describe` block
```php
describe('index', function () {
    it('should work', function() {
        expect(true)->toBeTrue();
    });
});
```
3. Run this test

**Expected behavior**
Test is ran.

**Screenshots**
Test result error
<img width="1639" alt="image" src="https://github.com/pestphp/pest-intellij/assets/370008/39d363a2-5de3-4226-8693-2b9071fafe67">

**Desktop:**
 - OS: macOs Ventura 13.3
 - IntelliJ Version: PHPStorm 2023.1.3
 - Plugin Version: 1.10.1

**Additional context**
Also, i'd like to mention that a test file with only `describe` blocks just can't be run, it works if i pull out one `test` or `if` at the "root" (and the file is not considered as a Pest file, see below screenshot)
<img width="32" alt="image" src="https://github.com/pestphp/pest-intellij/assets/370008/02130ba9-5e15-4fb9-8454-bd6baf0d331f">

**Comment by olivernybroe** [comment] 2023-07-21 09:19
Duplicate of #462

**Closed by olivernybroe** 2023-07-21 09:19 UTC
