### ISSUE TITLE
update failed for ActionGroup

### ISSUE THREAD

**Issue by CrazyBoy49z** [pestphp/pest-intellij#304] opened 2022-05-13 20:52 UTC
```
update failed for ActionGroup(com.intellij.execution.actions.RunContextAction, id=DebugClass) with text=Debug context configuration

java.lang.ClassCastException: class com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl$$Lambda$5955/0x0000000802ad4840 cannot be cast to class [Ljava.lang.Object; (com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl$$Lambda$5955/0x0000000802ad4840 is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6a0195af; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
	at com.intellij.util.SmartList.asArray(SmartList.java:160)
	at com.intellij.util.SmartList.resizeIfNecessary(SmartList.java:92)
	at com.intellij.util.SmartList.add(SmartList.java:81)
	at com.intellij.util.containers.ContainerUtil.add(ContainerUtil.java:1954)
	at com.jetbrains.php.config.interpreters.PhpInterpretersBaseManager.addListener(PhpInterpretersBaseManager.java:48)
	at com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl.addListener(PhpInterpretersManagerImpl.java:305)
	at com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl.<init>(PhpInterpretersManagerImpl.java:58)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:44)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.jetbrains.php.config.interpreters.PhpInterpretersManagerImpl.getInstance(PhpInterpretersManagerImpl.java:51)
	at com.jetbrains.php.config.PhpProjectConfigurationFacade.getInterpreter(PhpProjectConfigurationFacade.java:80)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfiguration.getInterpreter(PhpTestRunConfiguration.java:393)
	at com.jetbrains.php.testFramework.run.PhpTestRunConfiguration.<init>(PhpTestRunConfiguration.java:87)
	at com.pestphp.pest.configuration.PhpTestRunConfiguration.<init>(PhpTestRunConfiguration.java:16)
	at com.pestphp.pest.configuration.PestRunConfiguration.<init>(PestRunConfiguration.kt:33)
	at com.pestphp.pest.configuration.PestRunConfigurationType.createTemplateConfiguration(PestRunConfigurationType.kt:21)
	at com.intellij.execution.configurations.ConfigurationFactory.createTemplateConfiguration(ConfigurationFactory.java:64)
	at com.intellij.execution.impl.RunManagerImpl.createTemplateSettings$intellij_platform_execution_impl(RunManagerImpl.kt:353)
	at com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate(RunManagerImpl.kt:345)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:270)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfigurationStatic(RunConfigurationProducer.java:257)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfiguration(RunConfigurationProducer.java:247)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:96)
	at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:197)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:118)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:100)
	at com.intellij.execution.actions.PreferredProducerFind.createConfiguration(PreferredProducerFind.java:32)
	at com.intellij.execution.actions.ConfigurationContext.createConfiguration(ConfigurationContext.java:203)
	at com.intellij.execution.actions.ConfigurationContext.getConfiguration(ConfigurationContext.java:194)
	at com.intellij.execution.actions.BaseRunConfigurationAction.fullUpdate(BaseRunConfigurationAction.java:218)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:180)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:131)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:145)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:645)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:127)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:112)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:634)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:478)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:457)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1400)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:457)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:535)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:457)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1400)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:457)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:535)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:457)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1400)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:457)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:535)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:457)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1400)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:457)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:535)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:457)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1400)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:457)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:535)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:457)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1400)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:457)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:260)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$12(ActionUpdater.java:321)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$13(ActionUpdater.java:339)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$17(ActionUpdater.java:371)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:367)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:339)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$15(ActionUpdater.java:338)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by olivernybroe** [comment] 2022-05-14 07:36
Could you give a little context for what you were doing or how to reproduce?

**Comment by CrazyBoy49z** [comment] 2022-05-14 08:07
PhpStorm 2022.1.1
Build #PS-221.5591.58, built on May 12, 2022
Licensed to Yurij Finiv
Subscription is active until May 17, 2022.
Runtime version: 11.0.14.1+1-b2043.45 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.intellij.laf.enable.animation=true
    ide.windowSystem.autoShowProcessPopup=true
    run.processes.with.pty=TRUE
    editor.distraction.free.mode=true
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.2)
    pl.tigersoft.intellij.faker (1.2.0)
    lermitage.intellij.iconviewer (1.14.0.193)
    io.aesy.regex101 (0.2)
    intellij.webp (221.5591.26)
    ideanginx9 (0.1.9)
    dev.meanmail.plugin.nginx-intellij-plugin (2021.3-2022.1)
    de.ehmkah.projects.imgdiff (1.11.0)
    com.xiaobing1024.laravel (1.1.1)
    com.wakatime.intellij.plugin (13.1.14)
    com.ultrahob.zerolength.plugin2 (0.93)
    com.samdark.intellij-visual-studio-code-dark-plus (2.5)
    com.materkey.codepoints (1.0.2)
    com.mallowigi.idea (17.0)
    com.intellij.properties (221.5591.26)
    com.wix.sasslint (1.1.2)
    com.gmike.visual-studio-2019-dark (1.5.3)
    com.github.czy211.licensetemplate (2.0.0)
    com.github.copilot (1.1.20.1483-agent)
    com.github.chengpohi (1.8.1)
    cc.moky.intellij.plugin.svga-support (1.0.8)
    bundled-phpstorm-help (221.5591.58)
    com.intellij.jira (4.0.1)
    String Manipulation (9.4.0)
    LiveTemplatePreview (0.3)
    Key Promoter X (2022.1.1)
    zielu.gittoolbox (212.8.9)
    mobi.hsz.idea.gitignore (4.4.0)
    pers.fw.doc_en (1.1)
    nl.deschepers.laraveltinker (2.3.3)
    de.espend.idea.php.annotation (8.2.0)
    com.pestphp.pest-intellij (1.4.2)
    com.mallowigi.colorHighlighter (10.0.0)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    fr.adrienbrault.idea.symfony2plugin (2022.1.226)
    dev.nybroe.collector (0.3.5)
    com.alicannklc.laravel.snippets (1.1.1)
    nz.hailwood.inertiajs (0.1.4)
    jones.restarteslintaction.restart-eslint-action (0.0.1)
    intellij.prettierJS (221.5591.19)
    org.i18nally.jetbrainsideplugin (1.4.1.2)
    izhangzhihao.rainbow.brackets (6.23)
    com.mallowigi (64.0.0)
    ru.adelf.idea.dotenv (2022.1)
    com.laravel_idea.plugin (5.3.1.221)

**Comment by olivernybroe** [comment] 2022-05-15 12:51
I am suspecting this might be an issue in phpstorm itself and not in the plugin 🤔 
Will try to look a bit deeper into it.

**Comment by olivernybroe** [comment] 2022-08-09 07:29
Was not able to reproduce it, closing the issue, thanks for reporting though!

**Closed by olivernybroe** 2022-08-09 07:29 UTC
Labels: bug
